---
- hosts: all
  become: true
  vars:
    user: vagrant
  pre_tasks:
    - name: Dist update
      apt: upgrade=dist update_cache=yes cache_valid_time=86400 # a day
    - name: Package update
      apt: upgrade=full update_cache=yes cache_valid_time=86400
  roles:
    - role: geerlingguy.git
    - role: geerlingguy.java
    - role: geerlingguy.nodejs
    - role: geerlingguy.pip
    - role: geerlingguy.docker
  tasks:
  - name: Install desktop
    apt:
      name:
        - mate-desktop-environment-extras
        - lightdm
      state: present
  - name: Configure desktop
    shell: dpkg-reconfigure lightdm
  - name: Configure autologin
    blockinfile:
      path: /usr/share/lightdm/lightdm.conf.d/60-lightdm-gtk-greeter.conf
      create: yes
      block: |
        [SeatDefaults]
        greeter-session=lightdm-gtk-greeter
        autologin-user={{ user }}
  - name: Copy wallpaper # https://www.reddit.com/r/wallpaper/comments/b2vuhx/sr71_blackbird_19201080/eivjsti/
    copy: src=wallpaper.jpg dest=/home/{{ user }}/.wallpaper.jpg
  post_tasks:
  - name: Clean
    apt: autoremove=yes autoclean=yes