---
- hosts: all
  become: true
  vars:
    user: vagrant
  tasks:
  - name: Disable icons on desktop
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xfce4-desktop"
      property: "/desktop-icons/style"
      value_type: "int"
      value: "0"
  - name: Disable screensaver
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xfce4-power-manager"
      property: "/xfce4-power-manager/dpms-enabled"
      value_type: "bool"
      value: "false"
  - name: Never blank on AC
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xfce4-power-manager"
      property: "/xfce4-power-manager/blank-on-ac"
      value_type: "int"
      value: "0"
  - name: Never blank on battery
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xfce4-power-manager"
      property: "/xfce4-power-manager/blank-on-battery"
      value_type: "int"
      value: "0"
  - name: set WM theme
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xfwm4"
      property: "/general/theme"
      value_type: "string"
      value: "Circela"
  - name: set GTK theme
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xsettings"
      property: "/Net/ThemeName"
      value_type: "string"
      value: "Fantome"
  - name: set BG image
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
    become: "{{ user }}"
    xfconf:
      channel: "xfce4-desktop"
      property: "/backdrop/screen0/monitor0/workspace0/last-image"
      value_type: "string"
      value: "/usr/share/backgrounds/bgimage.jpg"
  - name: disable xScreenSaver
    lineinfile:
      path: /home/{{ user }}/.xscreensaver
      regexp: '^mode:'
      line: "mode: off"
